name: kd_rastreios_cp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons:
  get:
  bottom_navy_bar:
  http:
  path_provider:
  animations:
  timelines:
  adaptive_theme:
  google_fonts:
  background_fetch: ^1.0.0-nullsafety.2
  geolocator:
  flutter_local_notifications:
  provider:
  another_flushbar:
  flutter_easyloading:
  flutter_slidable:
  flutter_share:
  flutter_barcode_scanner:
  google_mobile_ads:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
